### ISSUE TITLE
Is this support window 7?

### ISSUE THREAD

**Issue by zhaodelong** [bjornedstrom/python-sha3#4]
When I try to build this on windows 7, I failed with these errors.

C:\Users\Delong\python-sha3>python setup.py build
running build
running build_py
running build_ext
building '_sha3' extension
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    packages=['sha3'])
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 337, in run
    self.build_extensions()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 446, in build_exte
nsions
    self.build_extension(ext)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 496, in build_exte
nsion
    depends=ext.depends)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsal
l
    raise ValueError(str(list(result.keys())))
ValueError: [u'path']

**Comment by bjornedstrom** [comment]
Thanks for the Report!

This is an issue I will probably not fix myself as I don't use Windows anywhere, but if anyone feel up for looking into it a pull request would be appreciated :)
